server:
  port: 8080

spring:
  datasource:
    url: "jdbc:mysql://127.0.0.1:3306/login_angular?useSSL=false&serverTimezone=Asia/Jakarta"
    username: root
    password: ""
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: "Asia/Jakarta"
  jackson:
    time-zone: "Asia/Jakarta"

app:
  jwt:
    secret: "this_is_a_very_long_random_secret_key_min_32_chars_1234567890"
    expiration-ms: 86400000

